import { NETWORK_NAME } from "./networkName";

export enum TESTNET_NETWORKS_ETHEREUM {
  GOERLI = "GOERLI",
  SEPOLIA = "SEPOLIA",
}
export enum TESTNET_NETWORKS_POLYGON {
  MUMBAI = "MUMBAI",
}

export const TESTNET_NETWORKS = Object.freeze({
  [NETWORK_NAME.ETHEREUM]: TESTNET_NETWORKS_ETHEREUM,
  [NETWORK_NAME.POLYGON]: TESTNET_NETWORKS_POLYGON,
} as const);

export type TestnetNetwork = {
  readonly [NETWORK_NAME.ETHEREUM]: TESTNET_NETWORKS_ETHEREUM;
  readonly [NETWORK_NAME.POLYGON]: TESTNET_NETWORKS_POLYGON;
};

export const defaultTestnetNetwork = Object.freeze({
  [NETWORK_NAME.ETHEREUM]: TESTNET_NETWORKS_ETHEREUM.SEPOLIA,
  [NETWORK_NAME.POLYGON]: TESTNET_NETWORKS_POLYGON.MUMBAI,
} as const);
